name: Push Empty Commit

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  push-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create and push empty commit
        run: |
          git config user.name "anthonymartinez1"
          git config user.email "anthony.martinez@uri.edu"
          git commit --allow-empty -m "Chore: 12-hour automated empty commit"
          git push origin main
